name: Global Format Check

# This workflow checks the formatting of the codebase using pre-commit hooks.

on: push

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955   # v4.3.0

    - name: Setup Java
      uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62   # v3.14.1
      with:
        distribution: zulu
        java-version: '21'

    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065   # v5.6.0
      with:
        python-version: '3.11'
        cache: pip
        check-latest: true
        update-environment: true

    - name: Run Pre-Commit
      uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd   # v3.0.1
      with:
        extra_args: --all-files
